package pe.gob.muni.apimercado.utils;

public class Http {
	public final static Integer CONTINUE=100;
	public final static Integer SWITCHING_PROTOCOLS=101;
	public final static Integer OK=200;
	public final static Integer CREATED=201;
	public final static Integer ACCEPTED=202;
	public final static Integer NON_AUTHORITATIVE_INFORMATION=203;
	public final static Integer NO_CONTENT=204;
	public final static Integer RESET_CONTENT=205;
	public final static Integer PARTIAL_CONTENT=206;
	public final static Integer MULTIPLE_CHOICES=300;
	public final static Integer MOVED_PERMANENTLY=301;
	public final static Integer FOUND=302;
	public final static Integer SEE_OTHER=303;
	public final static Integer NOT_MODIFIED=304;
	public final static Integer TEMPORARY_REDIRECT=307;
	public final static Integer PERMANENT_REDIRECT=308;
	public final static Integer BAD_REQUEST=400;
	public final static Integer UNAUTHORIZED=401;
	public final static Integer FORBIDDEN=403;
	public final static Integer NOT_FOUND=404;
	public final static Integer METHOD_NOT_ALLOWED=405;
	public final static Integer NOT_ACCEPTABLE=406;
	public final static Integer PROXY_AUTHENTICATION_REQUIRED=407;
	public final static Integer REQUEST_TIMEOUT=408;
	public final static Integer CONFLICT=409;
	public final static Integer GONE=410;
	public final static Integer LENGTH_REQUIRED=411;
	public final static Integer PRECONDITION_FAILED=412;
	public final static Integer PAYLOAD_TOO_LARGE=413;
	public final static Integer URI_TOO_LONG=414;
	public final static Integer UNSUPPORTED_MEDIA_TYPE=415;
	public final static Integer RANGE_NOT_SATISFIABLE=416;
	public final static Integer EXPECTATION_FAILED=417;
	public final static Integer I_AM_A_TEAPOT=418;
	public final static Integer UNPROCESSABLE_ENTITY=422;
	public final static Integer TOO_EARLY=425;
	public final static Integer UPGRADE_REQUIRED=426;
	public final static Integer PRECONDITION_REQUIRED=428;
	public final static Integer TOO_MANY_REQUESTS=429;
	public final static Integer REQUEST_HEADER_FIELDS_TOO_LARGE=431;
	public final static Integer UNAVAILABLE_FOR_LEGAL_REASONS=451;
	public final static Integer INTERNAL_SERVER_ERROR=500;
	public final static Integer NOT_IMPLEMENTED=501;
	public final static Integer PUERTA_DE_ENLACE_NO_VÁLIDA=502;
	public final static Integer SERVICIO_NO_DISPONIBLE=503;
	public final static Integer GATEWAY_TIMEOUT=504;
	public final static Integer HTTP_VERSION_NOT_SUPPORTED=505;
	public final static Integer NETWORK_AUTHENTICATION_REQUIRED=511;

}
